site_name: Center for Computational Mathematics         
 University of Colorado Denver
site_url: https://ccm-docs.readthedocs.io/en/latest/ 
nav:
    - Home: index.md
    - About: about.md
    - Clusters Guide: clusters_guide.md
    - Accounts and allocations: allocatiions.md
    - Alderaan Cluster: alderaan.md
    - Colibri Cluster: colibri.md
    - Score Cluster: score.md
    - Research Storage: storage.md
    - JupyterHub Server: jupyterhub.md
    - Local network: local.md
    - External Resources: external.md
    - Facilities, Equipment, and Other Resources: facilities.md
theme: readthedocs
