site_name: CCM CU Denver
site_url: https://ccm-docs.readthedocs.io/en/latest/ 
nav:
    - Home: index.md
    - About: about.md
    - Clusters guide: clusters_guide.md
    - Alderaan: alderaan.md
    - Colibri: colibri.md
    - Score: score.md
    - Research Storage: storage.md
    - Local network: local.md
theme: readthedocs
